---
title: "Stat 243 -- 02.08"
author: "Sharon Velpula"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    fig_height: 2.2
    fig_width: 4
  pdf_document:
    fig_height: 2.2
    fig_width: 4
  word_document:
    fig_height: 2.2
    fig_width: 4
---

```{r, setup, include = FALSE, message=FALSE}
# load packages that are going to be used
require(mosaic)      # this loads ggformula (for plotting), etc. too
require(Lock5withR)  # this loads data sets from our book

# Some customization. You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw())     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small")   # slightly smaller font for code
```

```{r}
advertising <- read.csv("https://trevorhastie.github.io/ISLR/Advertising.csv")
head(advertising)
lmPaper<- lm(sales ~ newspaper, data = advertising)
summary(lmPaper)

lmAllMedia <- lm(sales ~ newspaper+TV+radio, data = advertising)
summary(lmAllMedia)

lmNoPaper <- lm(sales ~ TV+radio, data = advertising)
summary(lmNoPaper)
```
Assumed 
some true model

$$ Sales = \beta_0 + \beta_1 * TV + \beta_2 * radio +noise $$
```{r}
#cor(advertising)
#cor(subset(advertising, select = c(TV, radio, newspaper, sales)))
cor(subset(advertising, select = c(TV, newspaper, sales)))
```

Up newspaper and radio ads together (0.35). Predicted value of newspaper is already covered by newspaper and radio. 
Correlation matrix will tell which pair of predictor variables are significant and which are not. 

```{r}
lm(medv ~ ., data = Boston) #Keeps all variables 
lm(medv ~ . - age, data = Boston) #Removes Age
lm(sales ~ TV +radio + tv:RADIO, )
```

