---
title: "Stat 243 -- Homework ??"
author: "Sharon Velpula"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    fig_height: 2.2
    fig_width: 4
  pdf_document:
    fig_height: 2.2
    fig_width: 4
  word_document:
    fig_height: 2.2
    fig_width: 4
---

```{r, setup, include = FALSE, message=FALSE}
# load packages that are going to be used
require(mosaic)      # this loads ggformula (for plotting), etc. too
require(Lock5withR)  # this loads data sets from our book

# Some customization. You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw())     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small")   # slightly smaller font for code
```

<!-- Put your work below here.  Put text in text chunks, code in R chunks. -->

```{r}
lmresult <- lm(PctTip ~ Bill, data = RestaurantTips)
gf_point(lmresult$residuals ~ lmresult$fitted) #first diagnostic plot
gf_qq(~lmresult$residuals) #second diagnostic plot 
```
$$ \widehat{\mbox{PctTip}} = 0.0488\times\mbox{Bill} + 15 $$

Using InkJetPrinters, do regression analysis using PPM as explanatory and Price
as response

Specifically, 
1. produce scatterplot w/ best fit line overlain
2. Generate/find the equation of this line
3. Give both 
- residuals vs. fit
- qqplot of residuals
Comment on appropriateness of SLM

4. Perform a model utility test 
5. Find coeff of determination
6. Find a 95% CI for beta 1

```{r}
lmresult<- lm(Price ~ PPM, data = InkjetPrinters)
gf_point(lmresult , data = InkjetPrinters) %>% gf_line()
```


