---
title: "Stat 243 -- Homework 1"
author: "Sharon Velpula"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  pdf_document:
    fig_height: 2.2
    fig_width: 4
  html_document:
    fig_height: 2.2
    fig_width: 4
  word_document:
    fig_height: 2.2
    fig_width: 4
---

```{r, setup, include = FALSE, message=FALSE}
# load packages that are going to be used
require(mosaic)      # this loads ggformula (for plotting), etc. too
require(Lock5withR)  # this loads data sets from our book

# Some customization. You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw())     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small")   # slightly smaller font for code
```

<!-- Put your work below here.  Put text in text chunks, code in R chunks. -->

### Importing dataset
```{r}
file <- read.csv("https://scofield.site/teaching/data/csv/ssurv.csv") 
head(file)
```
### Identification of variables
Categorical variable: sex

Discrete quantitative variable: numchildren

Continuous quantitative variable: gpa


### Command
```{r command}
filter(subset(file, select = c(sex, numchildren, gpa, smoker)), smoker == "Smoke")
```
### Standard Deviation Formula
s=$$\sqrt{\frac{1}{n-1}\sum_{i=1}^n (x_i - \overline x)^2}$$
