---
title: "Stat 243 -- Homework ??"
author: "Put your name here (keep the quotes)"
date: '`r format(Sys.Date(), "%B %d, %Y")`'
output: 
  html_document:
    fig_height: 2.2
    fig_width: 4
  pdf_document:
    fig_height: 2.2
    fig_width: 4
  word_document:
    fig_height: 2.2
    fig_width: 4
---

```{r, setup, include = FALSE, message=FALSE}
# load packages that are going to be used
require(mosaic)      # this loads ggformula (for plotting), etc. too
require(Lock5withR)  # this loads data sets from our book

# Some customization. You can alter or delete as desired (if you know what you are doing).

theme_set(theme_bw())     # change theme for ggplot2/ggformula

knitr::opts_chunk$set(
  tidy = FALSE,     # display code as typed (rather than reformatted)
  size = "small")   # slightly smaller font for code
```

<!-- Put your work below here.  Put text in text chunks, code in R chunks. -->

```{r}
age <- c(8, 9, 15, 4, 7, 3, 2)
cost <- c(58, 98, 102, 32, 60, 31, 25)
Q6 <- data.frame(age, cost)
summary(lm(cost ~ age, data = Q6))
```

```{r}
calories <- c(166, 116, 184, 154, 179, 189, 171, 130, 177)
sodium <- c(370, 169, 474, 440, 496, 500, 390, 280, 491)
Q15 <- data.frame(calories, sodium)
```

